version: 2
updates:
  - package-ecosystem: "github-actions"
    # Check the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "08:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "github-actions"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "08:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "npm"
      include: "scope"
