name: CI CD
on:
  push:
    branches:
      - main
    paths:
      # trigger on .github since workflows changed
      - '.github/**'
      - 'static/**'
      - 'src/**'
      - 'tests/**'
      # trigger on package*.json since dependencies changed
      - package.json
      - package-lock.json
      # trigger on config changes
      - playwright.config.ts
      - svelte.config.js
      - tsconfig.json
      - vite.config.ts
  pull_request:
    branches:
      - main
    paths:
      # trigger on .github since workflows changed
      - '.github/**'
      - 'static/**'
      - 'src/**'
      - 'tests/**'
      # trigger on package*.json since dependencies changed
      - package.json
      - package-lock.json
      # trigger on config changes
      - playwright.config.ts
      - svelte.config.js
      - tsconfig.json
      - vite.config.ts

jobs:
  continuous_integration:
    name: Continuous integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 18
          check-latest: true
      - name: Install dependencies
        run: npm ci
      - name: Check style rules
        run: npm run lint
      - name: Run unit tests and generate coverage report
        run: npm run test:coverage
      # see https://playwright.dev/docs/ci-intro#github-actions
      - name: Install browsers for integration tests
        run: npx playwright install --with-deps
      - name: Run integration tests
        run: npm run test:integration
    timeout-minutes: 15
  continuous_deployment:
    name: Continuous deployment
    needs: [continuous_integration]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 18
          check-latest: true
      - name: Install dependencies
        run: npm ci
      - name: Configure git
        env:
          USER_NAME: github-actions
          USER_EMAIL: github-actions@users.noreply.github.com
          ORIGIN: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        run: |
          git config user.name $USER_NAME
          git config user.email $USER_EMAIL
          git remote set-url origin $ORIGIN
      - name: Deploy to GitHub Pages
        run: npm run deploy
    timeout-minutes: 30
